/* Generated by gen-cfg-pressure-corpus; do not edit. */
#include "types.h"

#define KEEP __attribute__((noinline, used, section(".llvm_generated_cfg")))
extern u16 generated_cfg_selector(u16);
static u32 rotl32(u32 value, u16 amount) {
  return (value << amount) | (value >> (32U - amount));
}

KEEP u32 generated_cfg_0(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0x09ce4762UL;
  u32 v1 = b ^ 0xe56e9993UL;
  u32 v2 = rotl32(a ^ 0xfdc0b51dUL, 2U);
  u32 v3 = rotl32(b + 0x870f752cUL, 13U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 0U));
  u32 acc = (gate & 1U) ? v0 + v3 : v1 ^ v4;
  u16 i;
  for (i = 0U; i < (u16)((gate & 3U) + 1U); ++i) {
    u16 shift = (u16)(((i + 0U) & 15U) + 1U);
    if ((acc ^ i) & 1UL) acc = rotl32(acc + v2, shift) ^ v5;
    else acc = rotl32(acc ^ v1, shift) + v4;
  }
  return (acc ^ v0 ^ v1) + v2 + v3 + v4 + v5;
}

KEEP u32 generated_cfg_1(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0x5cf2fed9UL;
  u32 v1 = b ^ 0x661236edUL;
  u32 v2 = rotl32(a ^ 0x393f57caUL, 12U);
  u32 v3 = rotl32(b + 0xab09bb09UL, 13U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 1U));
  u32 acc;
  u32 tail = v0 ^ v1 ^ v2 ^ v3 ^ v4 ^ v5;
  switch (gate & 7U) {
  case 0: acc = v0 + v5; break;
  case 1: acc = v1 ^ v4; break;
  case 2: acc = v2 + v3; break;
  case 3: acc = v0 - v3; break;
  case 4: acc = v1 ^ v2 ^ v5; break;
  case 5: acc = v4 + v5; break;
  case 6: acc = v0 + v1 + v2; break;
  default: acc = v3 ^ v4; break;
  }
  return (gate & 0x10U) ? acc + tail : acc ^ tail;
}

KEEP u32 generated_cfg_2(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0x1172729dUL;
  u32 v1 = b ^ 0xbb1e5cadUL;
  u32 v2 = rotl32(a ^ 0x61f359e8UL, 3U);
  u32 v3 = rotl32(b + 0x5305cd6fUL, 8U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 2U));
  u32 acc = v0 + v1;
  u16 i;
  for (i = 0U; i < (u16)((gate & 7U) + 1U); ++i) {
    if (((i + gate) & 3U) == 0U) { acc ^= v2; continue; }
    acc += rotl32(v3 ^ i, (u16)(((i + 2U) & 15U) + 1U));
    if ((u16)(acc & 0xffUL) == (u16)0x9dU) break;
    acc ^= (i & 1U) ? v4 : v5;
  }
  return (acc + (v0 ^ v1)) ^ (v2 + v3) ^ v4 ^ v5;
}

KEEP u32 generated_cfg_3(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0xbfa35f5bUL;
  u32 v1 = b ^ 0x5d42fa9fUL;
  u32 v2 = rotl32(a ^ 0x40326977UL, 8U);
  u32 v3 = rotl32(b + 0xae8d70d9UL, 12U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 3U));
  u32 acc;
  u16 remaining;
  if (gate == 0U) return v0 ^ v5;
  if (gate & 1U) {
    if (gate & 2U) return v1 + v4 + v5;
    acc = v0 ^ v2;
  } else {
    acc = v1 + v3;
    if (gate & 4U) return acc ^ v4 ^ v5;
  }
  remaining = (u16)(((gate >> 3) & 3U) + 1U);
  for (; remaining != 0U; --remaining) {
    acc = rotl32(acc + v2, (u16)(((remaining + 3U) & 15U) + 1U));
    acc ^= (remaining & 1U) ? v4 : v5;
  }
  if (gate & 0x20U) return acc + v0 + v3;
  return acc ^ v1 ^ v2 ^ v4 ^ v5;
}

KEEP u32 generated_cfg_4(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0x125c42d2UL;
  u32 v1 = b ^ 0xdacfb5f1UL;
  u32 v2 = rotl32(a ^ 0xa241fae9UL, 3U);
  u32 v3 = rotl32(b + 0x3e8e1887UL, 12U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 4U));
  u32 acc = v0;
  u16 i, j;
  for (i = 0U; i < (u16)((gate & 3U) + 1U); ++i) {
    for (j = 0U; j < (u16)(((gate >> 2) & 3U) + 1U); ++j) {
      u16 shift = (u16)(((i + j + 4U) & 15U) + 1U);
      u32 term = rotl32(v1 + ((u32)i << 16) + j, shift);
      if ((i + j + gate) & 1U) acc = (acc + term) ^ v4;
      else acc = rotl32(acc ^ term, shift) + v5;
    }
    acc ^= v2 + v3;
  }
  return acc ^ v0 ^ v1 ^ v2 ^ v3 ^ v4 ^ v5;
}

KEEP u32 generated_cfg_5(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0x4e4e4f48UL;
  u32 v1 = b ^ 0x73469ffbUL;
  u32 v2 = rotl32(a ^ 0xb78c5b47UL, 10U);
  u32 v3 = rotl32(b + 0xa0700395UL, 15U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 5U));
  u32 acc = v0 ^ v1;
  u16 i = 0U;
  u16 limit = (u16)((gate & 7U) + 1U);
  do {
    u32 selected = (i & 1U) ? v2 : v3;
    acc = rotl32(acc + selected, (u16)(((i + 5U) & 15U) + 1U));
    if (gate & (u16)(1U << (i & 3U))) acc ^= v4;
    else acc += v5;
    ++i;
  } while (i < limit);
  if ((gate & 0x30U) == 0x30U) return acc ^ v0 ^ v3;
  return (acc + v1 + v2) ^ v4 ^ v5;
}

KEEP u32 generated_cfg_6(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0xa05c8114UL;
  u32 v1 = b ^ 0x3fbd3c4bUL;
  u32 v2 = rotl32(a ^ 0x9eb61a71UL, 5U);
  u32 v3 = rotl32(b + 0xe2fa852dUL, 8U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 6U));
  u32 acc = v0 + v1;
  u16 i;
  for (i = 0U; i < (u16)((gate & 3U) + 2U); ++i) {
    u16 step = generated_cfg_selector((u16)(gate + i + 6U));
    acc = rotl32(acc ^ ((step & 1U) ? v2 : v3),
                 (u16)(((i + 6U) & 15U) + 1U));
    acc += (step & 2U) ? v4 : v5;
  }
  return acc ^ v0 ^ v1 ^ v2 ^ v3 ^ v4 ^ v5;
}

KEEP u32 generated_cfg_7(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0xf9b0fc42UL;
  u32 v1 = b ^ 0x2121249eUL;
  u32 v2 = rotl32(a ^ 0xb3ee2ea7UL, 16U);
  u32 v3 = rotl32(b + 0xb16442faUL, 5U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 7U));
  u32 acc = v0 + v5;
  if (gate & 1U) goto odd;
  acc ^= v1;
  if (gate & 2U) goto tail;
  acc += v2;
  goto merge;
odd:
  acc -= v3;
  if (gate & 4U) goto tail;
  acc ^= v4;
merge:
  acc = rotl32(acc, 8U) ^ v5;
tail:
  if (gate & 8U) acc += v0;
  else acc ^= v2;
  return acc ^ v1 ^ v3 ^ v4;
}

KEEP u32 generated_cfg_8(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0x1e58d287UL;
  u32 v1 = b ^ 0x850e20e3UL;
  u32 v2 = rotl32(a ^ 0x635e6d2aUL, 4U);
  u32 v3 = rotl32(b + 0x719430b7UL, 1U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 8U));
  u32 acc = (gate & 1U) ? v0 + v3 : v1 ^ v4;
  u16 i;
  for (i = 0U; i < (u16)((gate & 3U) + 1U); ++i) {
    u16 shift = (u16)(((i + 8U) & 15U) + 1U);
    if ((acc ^ i) & 1UL) acc = rotl32(acc + v2, shift) ^ v5;
    else acc = rotl32(acc ^ v1, shift) + v4;
  }
  return (acc ^ v0 ^ v1) + v2 + v3 + v4 + v5;
}

KEEP u32 generated_cfg_9(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0x07d7c5b6UL;
  u32 v1 = b ^ 0x134e3ac6UL;
  u32 v2 = rotl32(a ^ 0x56c4896dUL, 1U);
  u32 v3 = rotl32(b + 0x3ac019b9UL, 3U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 9U));
  u32 acc;
  u32 tail = v0 ^ v1 ^ v2 ^ v3 ^ v4 ^ v5;
  switch (gate & 7U) {
  case 0: acc = v0 + v5; break;
  case 1: acc = v1 ^ v4; break;
  case 2: acc = v2 + v3; break;
  case 3: acc = v0 - v3; break;
  case 4: acc = v1 ^ v2 ^ v5; break;
  case 5: acc = v4 + v5; break;
  case 6: acc = v0 + v1 + v2; break;
  default: acc = v3 ^ v4; break;
  }
  return (gate & 0x10U) ? acc + tail : acc ^ tail;
}

KEEP u32 generated_cfg_10(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0x07138d02UL;
  u32 v1 = b ^ 0xa0cd3d3bUL;
  u32 v2 = rotl32(a ^ 0xea218f4eUL, 1U);
  u32 v3 = rotl32(b + 0xa2cc77eaUL, 5U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 10U));
  u32 acc = v0 + v1;
  u16 i;
  for (i = 0U; i < (u16)((gate & 7U) + 1U); ++i) {
    if (((i + gate) & 3U) == 0U) { acc ^= v2; continue; }
    acc += rotl32(v3 ^ i, (u16)(((i + 10U) & 15U) + 1U));
    if ((u16)(acc & 0xffUL) == (u16)0x02U) break;
    acc ^= (i & 1U) ? v4 : v5;
  }
  return (acc + (v0 ^ v1)) ^ (v2 + v3) ^ v4 ^ v5;
}

KEEP u32 generated_cfg_11(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0xaa151fb2UL;
  u32 v1 = b ^ 0x35883323UL;
  u32 v2 = rotl32(a ^ 0x4e651075UL, 6U);
  u32 v3 = rotl32(b + 0x61130e40UL, 7U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 11U));
  u32 acc;
  u16 remaining;
  if (gate == 0U) return v0 ^ v5;
  if (gate & 1U) {
    if (gate & 2U) return v1 + v4 + v5;
    acc = v0 ^ v2;
  } else {
    acc = v1 + v3;
    if (gate & 4U) return acc ^ v4 ^ v5;
  }
  remaining = (u16)(((gate >> 3) & 3U) + 1U);
  for (; remaining != 0U; --remaining) {
    acc = rotl32(acc + v2, (u16)(((remaining + 11U) & 15U) + 1U));
    acc ^= (remaining & 1U) ? v4 : v5;
  }
  if (gate & 0x20U) return acc + v0 + v3;
  return acc ^ v1 ^ v2 ^ v4 ^ v5;
}

KEEP u32 generated_cfg_12(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0x1bbacb8dUL;
  u32 v1 = b ^ 0x1ba217e8UL;
  u32 v2 = rotl32(a ^ 0x72b853a7UL, 4U);
  u32 v3 = rotl32(b + 0x615d77e1UL, 4U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 12U));
  u32 acc = v0;
  u16 i, j;
  for (i = 0U; i < (u16)((gate & 3U) + 1U); ++i) {
    for (j = 0U; j < (u16)(((gate >> 2) & 3U) + 1U); ++j) {
      u16 shift = (u16)(((i + j + 12U) & 15U) + 1U);
      u32 term = rotl32(v1 + ((u32)i << 16) + j, shift);
      if ((i + j + gate) & 1U) acc = (acc + term) ^ v4;
      else acc = rotl32(acc ^ term, shift) + v5;
    }
    acc ^= v2 + v3;
  }
  return acc ^ v0 ^ v1 ^ v2 ^ v3 ^ v4 ^ v5;
}

KEEP u32 generated_cfg_13(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0x3b873611UL;
  u32 v1 = b ^ 0x75ea6ed3UL;
  u32 v2 = rotl32(a ^ 0x3e324babUL, 8U);
  u32 v3 = rotl32(b + 0x9fa51108UL, 15U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 13U));
  u32 acc = v0 ^ v1;
  u16 i = 0U;
  u16 limit = (u16)((gate & 7U) + 1U);
  do {
    u32 selected = (i & 1U) ? v2 : v3;
    acc = rotl32(acc + selected, (u16)(((i + 13U) & 15U) + 1U));
    if (gate & (u16)(1U << (i & 3U))) acc ^= v4;
    else acc += v5;
    ++i;
  } while (i < limit);
  if ((gate & 0x30U) == 0x30U) return acc ^ v0 ^ v3;
  return (acc + v1 + v2) ^ v4 ^ v5;
}

KEEP u32 generated_cfg_14(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0x8d05f68aUL;
  u32 v1 = b ^ 0x49414360UL;
  u32 v2 = rotl32(a ^ 0x44830d36UL, 2U);
  u32 v3 = rotl32(b + 0x819e2b24UL, 10U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 14U));
  u32 acc = v0 + v1;
  u16 i;
  for (i = 0U; i < (u16)((gate & 3U) + 2U); ++i) {
    u16 step = generated_cfg_selector((u16)(gate + i + 14U));
    acc = rotl32(acc ^ ((step & 1U) ? v2 : v3),
                 (u16)(((i + 14U) & 15U) + 1U));
    acc += (step & 2U) ? v4 : v5;
  }
  return acc ^ v0 ^ v1 ^ v2 ^ v3 ^ v4 ^ v5;
}

KEEP u32 generated_cfg_15(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0xdbaba279UL;
  u32 v1 = b ^ 0x537e64ebUL;
  u32 v2 = rotl32(a ^ 0x638a285aUL, 12U);
  u32 v3 = rotl32(b + 0xf6ae185aUL, 11U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 15U));
  u32 acc = v0 + v5;
  if (gate & 1U) goto odd;
  acc ^= v1;
  if (gate & 2U) goto tail;
  acc += v2;
  goto merge;
odd:
  acc -= v3;
  if (gate & 4U) goto tail;
  acc ^= v4;
merge:
  acc = rotl32(acc, 16U) ^ v5;
tail:
  if (gate & 8U) acc += v0;
  else acc ^= v2;
  return acc ^ v1 ^ v3 ^ v4;
}

KEEP u32 generated_cfg_16(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0x810d1388UL;
  u32 v1 = b ^ 0x4cfc44f6UL;
  u32 v2 = rotl32(a ^ 0x483e3e27UL, 1U);
  u32 v3 = rotl32(b + 0x70a9a29aUL, 10U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 16U));
  u32 acc = (gate & 1U) ? v0 + v3 : v1 ^ v4;
  u16 i;
  for (i = 0U; i < (u16)((gate & 3U) + 1U); ++i) {
    u16 shift = (u16)(((i + 16U) & 15U) + 1U);
    if ((acc ^ i) & 1UL) acc = rotl32(acc + v2, shift) ^ v5;
    else acc = rotl32(acc ^ v1, shift) + v4;
  }
  return (acc ^ v0 ^ v1) + v2 + v3 + v4 + v5;
}

KEEP u32 generated_cfg_17(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0xdba2dc07UL;
  u32 v1 = b ^ 0x846dfed6UL;
  u32 v2 = rotl32(a ^ 0x4d5342adUL, 12U);
  u32 v3 = rotl32(b + 0x85d8f5eeUL, 1U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 17U));
  u32 acc;
  u32 tail = v0 ^ v1 ^ v2 ^ v3 ^ v4 ^ v5;
  switch (gate & 7U) {
  case 0: acc = v0 + v5; break;
  case 1: acc = v1 ^ v4; break;
  case 2: acc = v2 + v3; break;
  case 3: acc = v0 - v3; break;
  case 4: acc = v1 ^ v2 ^ v5; break;
  case 5: acc = v4 + v5; break;
  case 6: acc = v0 + v1 + v2; break;
  default: acc = v3 ^ v4; break;
  }
  return (gate & 0x10U) ? acc + tail : acc ^ tail;
}

KEEP u32 generated_cfg_18(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0xf7ca73dcUL;
  u32 v1 = b ^ 0x8f844f84UL;
  u32 v2 = rotl32(a ^ 0xc8ed5b7eUL, 15U);
  u32 v3 = rotl32(b + 0x13d7fd5fUL, 2U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 18U));
  u32 acc = v0 + v1;
  u16 i;
  for (i = 0U; i < (u16)((gate & 7U) + 1U); ++i) {
    if (((i + gate) & 3U) == 0U) { acc ^= v2; continue; }
    acc += rotl32(v3 ^ i, (u16)(((i + 18U) & 15U) + 1U));
    if ((u16)(acc & 0xffUL) == (u16)0xdcU) break;
    acc ^= (i & 1U) ? v4 : v5;
  }
  return (acc + (v0 ^ v1)) ^ (v2 + v3) ^ v4 ^ v5;
}

KEEP u32 generated_cfg_19(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0x63f10741UL;
  u32 v1 = b ^ 0x2039df6dUL;
  u32 v2 = rotl32(a ^ 0x615a2267UL, 13U);
  u32 v3 = rotl32(b + 0x87cccd6cUL, 5U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 19U));
  u32 acc;
  u16 remaining;
  if (gate == 0U) return v0 ^ v5;
  if (gate & 1U) {
    if (gate & 2U) return v1 + v4 + v5;
    acc = v0 ^ v2;
  } else {
    acc = v1 + v3;
    if (gate & 4U) return acc ^ v4 ^ v5;
  }
  remaining = (u16)(((gate >> 3) & 3U) + 1U);
  for (; remaining != 0U; --remaining) {
    acc = rotl32(acc + v2, (u16)(((remaining + 19U) & 15U) + 1U));
    acc ^= (remaining & 1U) ? v4 : v5;
  }
  if (gate & 0x20U) return acc + v0 + v3;
  return acc ^ v1 ^ v2 ^ v4 ^ v5;
}

KEEP u32 generated_cfg_20(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0xd24909dcUL;
  u32 v1 = b ^ 0x9d2cfcc5UL;
  u32 v2 = rotl32(a ^ 0x543fee7fUL, 11U);
  u32 v3 = rotl32(b + 0x97fb0a67UL, 4U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 20U));
  u32 acc = v0;
  u16 i, j;
  for (i = 0U; i < (u16)((gate & 3U) + 1U); ++i) {
    for (j = 0U; j < (u16)(((gate >> 2) & 3U) + 1U); ++j) {
      u16 shift = (u16)(((i + j + 20U) & 15U) + 1U);
      u32 term = rotl32(v1 + ((u32)i << 16) + j, shift);
      if ((i + j + gate) & 1U) acc = (acc + term) ^ v4;
      else acc = rotl32(acc ^ term, shift) + v5;
    }
    acc ^= v2 + v3;
  }
  return acc ^ v0 ^ v1 ^ v2 ^ v3 ^ v4 ^ v5;
}

KEEP u32 generated_cfg_21(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0x2045b6bcUL;
  u32 v1 = b ^ 0x44ddc355UL;
  u32 v2 = rotl32(a ^ 0x6a54bcceUL, 5U);
  u32 v3 = rotl32(b + 0x446d4728UL, 9U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 21U));
  u32 acc = v0 ^ v1;
  u16 i = 0U;
  u16 limit = (u16)((gate & 7U) + 1U);
  do {
    u32 selected = (i & 1U) ? v2 : v3;
    acc = rotl32(acc + selected, (u16)(((i + 21U) & 15U) + 1U));
    if (gate & (u16)(1U << (i & 3U))) acc ^= v4;
    else acc += v5;
    ++i;
  } while (i < limit);
  if ((gate & 0x30U) == 0x30U) return acc ^ v0 ^ v3;
  return (acc + v1 + v2) ^ v4 ^ v5;
}

KEEP u32 generated_cfg_22(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0x7d8e1cecUL;
  u32 v1 = b ^ 0x7c6bbf45UL;
  u32 v2 = rotl32(a ^ 0x7be04a04UL, 16U);
  u32 v3 = rotl32(b + 0x26be99d4UL, 16U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 22U));
  u32 acc = v0 + v1;
  u16 i;
  for (i = 0U; i < (u16)((gate & 3U) + 2U); ++i) {
    u16 step = generated_cfg_selector((u16)(gate + i + 22U));
    acc = rotl32(acc ^ ((step & 1U) ? v2 : v3),
                 (u16)(((i + 22U) & 15U) + 1U));
    acc += (step & 2U) ? v4 : v5;
  }
  return acc ^ v0 ^ v1 ^ v2 ^ v3 ^ v4 ^ v5;
}

KEEP u32 generated_cfg_23(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0x450801d6UL;
  u32 v1 = b ^ 0xe36e8aafUL;
  u32 v2 = rotl32(a ^ 0x755505f2UL, 9U);
  u32 v3 = rotl32(b + 0x688ecfe7UL, 13U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 23U));
  u32 acc = v0 + v5;
  if (gate & 1U) goto odd;
  acc ^= v1;
  if (gate & 2U) goto tail;
  acc += v2;
  goto merge;
odd:
  acc -= v3;
  if (gate & 4U) goto tail;
  acc ^= v4;
merge:
  acc = rotl32(acc, 8U) ^ v5;
tail:
  if (gate & 8U) acc += v0;
  else acc ^= v2;
  return acc ^ v1 ^ v3 ^ v4;
}

KEEP u32 generated_cfg_24(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0x9f3c9c9eUL;
  u32 v1 = b ^ 0x994403e9UL;
  u32 v2 = rotl32(a ^ 0x3e1cc1d5UL, 4U);
  u32 v3 = rotl32(b + 0x62e06a06UL, 4U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 24U));
  u32 acc = (gate & 1U) ? v0 + v3 : v1 ^ v4;
  u16 i;
  for (i = 0U; i < (u16)((gate & 3U) + 1U); ++i) {
    u16 shift = (u16)(((i + 24U) & 15U) + 1U);
    if ((acc ^ i) & 1UL) acc = rotl32(acc + v2, shift) ^ v5;
    else acc = rotl32(acc ^ v1, shift) + v4;
  }
  return (acc ^ v0 ^ v1) + v2 + v3 + v4 + v5;
}

KEEP u32 generated_cfg_25(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0x9bb32716UL;
  u32 v1 = b ^ 0x15628f7eUL;
  u32 v2 = rotl32(a ^ 0xd520ca38UL, 4U);
  u32 v3 = rotl32(b + 0x40922d6bUL, 3U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 25U));
  u32 acc;
  u32 tail = v0 ^ v1 ^ v2 ^ v3 ^ v4 ^ v5;
  switch (gate & 7U) {
  case 0: acc = v0 + v5; break;
  case 1: acc = v1 ^ v4; break;
  case 2: acc = v2 + v3; break;
  case 3: acc = v0 - v3; break;
  case 4: acc = v1 ^ v2 ^ v5; break;
  case 5: acc = v4 + v5; break;
  case 6: acc = v0 + v1 + v2; break;
  default: acc = v3 ^ v4; break;
  }
  return (gate & 0x10U) ? acc + tail : acc ^ tail;
}

KEEP u32 generated_cfg_26(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0xa2d6b174UL;
  u32 v1 = b ^ 0xebf96a08UL;
  u32 v2 = rotl32(a ^ 0x11b923d4UL, 5U);
  u32 v3 = rotl32(b + 0x8db49f95UL, 14U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 26U));
  u32 acc = v0 + v1;
  u16 i;
  for (i = 0U; i < (u16)((gate & 7U) + 1U); ++i) {
    if (((i + gate) & 3U) == 0U) { acc ^= v2; continue; }
    acc += rotl32(v3 ^ i, (u16)(((i + 26U) & 15U) + 1U));
    if ((u16)(acc & 0xffUL) == (u16)0x74U) break;
    acc ^= (i & 1U) ? v4 : v5;
  }
  return (acc + (v0 ^ v1)) ^ (v2 + v3) ^ v4 ^ v5;
}

KEEP u32 generated_cfg_27(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0xd6802676UL;
  u32 v1 = b ^ 0x9b9f6571UL;
  u32 v2 = rotl32(a ^ 0x911ea3c9UL, 11U);
  u32 v3 = rotl32(b + 0xe9938e3aUL, 4U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 27U));
  u32 acc;
  u16 remaining;
  if (gate == 0U) return v0 ^ v5;
  if (gate & 1U) {
    if (gate & 2U) return v1 + v4 + v5;
    acc = v0 ^ v2;
  } else {
    acc = v1 + v3;
    if (gate & 4U) return acc ^ v4 ^ v5;
  }
  remaining = (u16)(((gate >> 3) & 3U) + 1U);
  for (; remaining != 0U; --remaining) {
    acc = rotl32(acc + v2, (u16)(((remaining + 27U) & 15U) + 1U));
    acc ^= (remaining & 1U) ? v4 : v5;
  }
  if (gate & 0x20U) return acc + v0 + v3;
  return acc ^ v1 ^ v2 ^ v4 ^ v5;
}

KEEP u32 generated_cfg_28(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0x92c4c010UL;
  u32 v1 = b ^ 0x521e6b13UL;
  u32 v2 = rotl32(a ^ 0x70f4d10dUL, 3U);
  u32 v3 = rotl32(b + 0xb0758887UL, 11U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 28U));
  u32 acc = v0;
  u16 i, j;
  for (i = 0U; i < (u16)((gate & 3U) + 1U); ++i) {
    for (j = 0U; j < (u16)(((gate >> 2) & 3U) + 1U); ++j) {
      u16 shift = (u16)(((i + j + 28U) & 15U) + 1U);
      u32 term = rotl32(v1 + ((u32)i << 16) + j, shift);
      if ((i + j + gate) & 1U) acc = (acc + term) ^ v4;
      else acc = rotl32(acc ^ term, shift) + v5;
    }
    acc ^= v2 + v3;
  }
  return acc ^ v0 ^ v1 ^ v2 ^ v3 ^ v4 ^ v5;
}

KEEP u32 generated_cfg_29(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0x2dc86e95UL;
  u32 v1 = b ^ 0x23410d98UL;
  u32 v2 = rotl32(a ^ 0x5cb390c1UL, 6U);
  u32 v3 = rotl32(b + 0xfbdf5514UL, 5U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 29U));
  u32 acc = v0 ^ v1;
  u16 i = 0U;
  u16 limit = (u16)((gate & 7U) + 1U);
  do {
    u32 selected = (i & 1U) ? v2 : v3;
    acc = rotl32(acc + selected, (u16)(((i + 29U) & 15U) + 1U));
    if (gate & (u16)(1U << (i & 3U))) acc ^= v4;
    else acc += v5;
    ++i;
  } while (i < limit);
  if ((gate & 0x30U) == 0x30U) return acc ^ v0 ^ v3;
  return (acc + v1 + v2) ^ v4 ^ v5;
}

KEEP u32 generated_cfg_30(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0x3ec668eaUL;
  u32 v1 = b ^ 0x88b171e7UL;
  u32 v2 = rotl32(a ^ 0x77359681UL, 8U);
  u32 v3 = rotl32(b + 0x795f5a13UL, 2U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 30U));
  u32 acc = v0 + v1;
  u16 i;
  for (i = 0U; i < (u16)((gate & 3U) + 2U); ++i) {
    u16 step = generated_cfg_selector((u16)(gate + i + 30U));
    acc = rotl32(acc ^ ((step & 1U) ? v2 : v3),
                 (u16)(((i + 30U) & 15U) + 1U));
    acc += (step & 2U) ? v4 : v5;
  }
  return acc ^ v0 ^ v1 ^ v2 ^ v3 ^ v4 ^ v5;
}

KEEP u32 generated_cfg_31(u32 a, u32 b, u16 selector) {
  u32 v0 = a + 0xd1b310bdUL;
  u32 v1 = b ^ 0xc739c48fUL;
  u32 v2 = rotl32(a ^ 0x0aa3303bUL, 11U);
  u32 v3 = rotl32(b + 0xf828ab49UL, 9U);
  u32 v4 = v0 ^ v2;
  u32 v5 = v1 + v3;
  u16 gate = generated_cfg_selector((u16)(selector ^ 31U));
  u32 acc = v0 + v5;
  if (gate & 1U) goto odd;
  acc ^= v1;
  if (gate & 2U) goto tail;
  acc += v2;
  goto merge;
odd:
  acc -= v3;
  if (gate & 4U) goto tail;
  acc ^= v4;
merge:
  acc = rotl32(acc, 16U) ^ v5;
tail:
  if (gate & 8U) acc += v0;
  else acc ^= v2;
  return acc ^ v1 ^ v3 ^ v4;
}

KEEP u32 llvm_generated_cfg_eval(u16 kernel, u32 a, u32 b, u16 selector) {
  switch (kernel) {
  case 0U: return generated_cfg_0(a, b, selector);
  case 1U: return generated_cfg_1(a, b, selector);
  case 2U: return generated_cfg_2(a, b, selector);
  case 3U: return generated_cfg_3(a, b, selector);
  case 4U: return generated_cfg_4(a, b, selector);
  case 5U: return generated_cfg_5(a, b, selector);
  case 6U: return generated_cfg_6(a, b, selector);
  case 7U: return generated_cfg_7(a, b, selector);
  case 8U: return generated_cfg_8(a, b, selector);
  case 9U: return generated_cfg_9(a, b, selector);
  case 10U: return generated_cfg_10(a, b, selector);
  case 11U: return generated_cfg_11(a, b, selector);
  case 12U: return generated_cfg_12(a, b, selector);
  case 13U: return generated_cfg_13(a, b, selector);
  case 14U: return generated_cfg_14(a, b, selector);
  case 15U: return generated_cfg_15(a, b, selector);
  case 16U: return generated_cfg_16(a, b, selector);
  case 17U: return generated_cfg_17(a, b, selector);
  case 18U: return generated_cfg_18(a, b, selector);
  case 19U: return generated_cfg_19(a, b, selector);
  case 20U: return generated_cfg_20(a, b, selector);
  case 21U: return generated_cfg_21(a, b, selector);
  case 22U: return generated_cfg_22(a, b, selector);
  case 23U: return generated_cfg_23(a, b, selector);
  case 24U: return generated_cfg_24(a, b, selector);
  case 25U: return generated_cfg_25(a, b, selector);
  case 26U: return generated_cfg_26(a, b, selector);
  case 27U: return generated_cfg_27(a, b, selector);
  case 28U: return generated_cfg_28(a, b, selector);
  case 29U: return generated_cfg_29(a, b, selector);
  case 30U: return generated_cfg_30(a, b, selector);
  case 31U: return generated_cfg_31(a, b, selector);
  default: return 0UL;
  }
}
