#include "functions.h"
#include "c166_test.h"
#include "types.h"

#define ABI_LAYOUT_ATTRIBUTE C166_NOINLINE

DEFINE_LAYOUT_FUNCTIONS(c166, ABI_LAYOUT_ATTRIBUTE, ABI_LAYOUT_ATTRIBUTE,
                        ABI_LAYOUT_ATTRIBUTE, ABI_LAYOUT_ATTRIBUTE,
                        ABI_LAYOUT_ATTRIBUTE, ABI_LAYOUT_ATTRIBUTE,
                        ABI_LAYOUT_ATTRIBUTE)

DEFINE_LAYOUT_BIT_EDGES_FUNCTION(c166, ABI_LAYOUT_ATTRIBUTE)

DEFINE_LAYOUT_NESTED_PACKED_FUNCTION(c166, ABI_LAYOUT_ATTRIBUTE)
