/* Generated by tools/gen-type-semantics-corpus. */
typedef unsigned char u8;
typedef signed char s8;
typedef unsigned int u16;
typedef signed int s16;
typedef unsigned long u32;
typedef signed long s32;
#define KEEP __attribute__((noinline, used, section(".llvm_generated_types")))

KEEP u8 generated_type_00_u8(u8 a, u8 b) {
  u16 x = (u16)a + (u16)b + 0x21U;
  x ^= (u16)((u16)a << (b & 7U));
  return (u8)(x + (u16)(a * b));
}

KEEP u8 generated_type_01_u8(u8 a, u8 b) {
  u16 x = (u16)a + (u16)b + 0xacU;
  x ^= (u16)((u16)a << (b & 7U));
  return (u8)(x + (u16)(a * b));
}

KEEP s16 generated_type_02_s8(s8 a, s8 b) {
  s16 product = (s16)((s16)a * (s16)b);
  s16 delta = (s16)a - (s16)b;
  return (s16)(product / 4 + delta);
}

KEEP s16 generated_type_03_s8(s8 a, s8 b) {
  s16 product = (s16)((s16)a * (s16)b);
  s16 delta = (s16)a - (s16)b;
  return (s16)(product / 1 + delta);
}

KEEP u16 generated_type_04_u16(u16 a, u16 b) {
  u16 shift = (u16)(b & 15U);
  u16 divisor = (u16)(b | 1U);
  u16 value = (u16)(a * 0x53f5U + b);
  return (u16)((value << shift) ^ (a / divisor) ^ (a % divisor));
}

KEEP u16 generated_type_05_u16(u16 a, u16 b) {
  u16 shift = (u16)(b & 15U);
  u16 divisor = (u16)(b | 1U);
  u16 value = (u16)(a * 0x4dc9U + b);
  return (u16)((value << shift) ^ (a / divisor) ^ (a % divisor));
}

KEEP s32 generated_type_06_s16(s16 a, s16 b) {
  s32 wide_a = (s32)a;
  s32 wide_b = (s32)b;
  return wide_a * wide_b + wide_a - wide_b + 0x3d05L;
}

KEEP s32 generated_type_07_s16(s16 a, s16 b) {
  s32 wide_a = (s32)a;
  s32 wide_b = (s32)b;
  return wide_a * wide_b + wide_a - wide_b + 0x1608L;
}

KEEP u32 generated_type_08_u32(u32 a, u32 b) {
  u16 shift = (u16)(b & 31UL);
  u32 divisor = b | 1UL;
  u32 value = a * 0x652ae58bUL + b;
  return (value << shift) ^ (a >> shift) ^ (a / divisor) ^ (a % divisor);
}

KEEP u32 generated_type_09_u32(u32 a, u32 b) {
  u16 shift = (u16)(b & 31UL);
  u32 divisor = b | 1UL;
  u32 value = a * 0x0aec91a7UL + b;
  return (value << shift) ^ (a >> shift) ^ (a / divisor) ^ (a % divisor);
}

KEEP u32 generated_type_10_compare(s32 a, s32 b, u16 selector) {
  if ((selector & 3U) == 0U) return a < b ? (u32)a : (u32)b;
  if ((selector & 3U) == 1U) return a >= b ? (u32)(a - b) : (u32)(b - a);
  if ((selector & 3U) == 2U)
    return a == b ? 0x83df84abUL : (u32)(a ^ b);
  return a != 0L && b != 0L ? (u32)a : (u32)b;
}

KEEP u32 generated_type_11_compare(s32 a, s32 b, u16 selector) {
  if ((selector & 3U) == 0U) return a < b ? (u32)a : (u32)b;
  if ((selector & 3U) == 1U) return a >= b ? (u32)(a - b) : (u32)(b - a);
  if ((selector & 3U) == 2U)
    return a == b ? 0x1a117cceUL : (u32)(a ^ b);
  return a != 0L && b != 0L ? (u32)a : (u32)b;
}

KEEP u32 generated_type_12_loop(u16 count, u32 value) {
  u16 i;
  for (i = 0U; i < (u16)(count & 15U); ++i) {
    value = (value << 3) | (value >> 29);
    value ^= (u32)i + 0x849c674aUL;
  }
  return value;
}

KEEP u32 generated_type_13_loop(u16 count, u32 value) {
  u16 i;
  for (i = 0U; i < (u16)(count & 15U); ++i) {
    value = (value << 3) | (value >> 29);
    value ^= (u32)i + 0x06d14d70UL;
  }
  return value;
}

KEEP u32 generated_type_14_switch(u16 selector, u32 value) {
  switch (selector & 7U) {
  case 0: return value ^ 0x032fUL;
  case 1: return value ^ 0x4032UL;
  case 2: return value ^ 0x9403UL;
  case 3: return value ^ 0x0940UL;
  case 4: return value ^ 0xc094UL;
  case 5: return value ^ 0x0c09UL;
  case 6: return value + 0x032fUL;
  default: return value - 0xc094UL;
  }
}

KEEP u32 generated_type_15_switch(u16 selector, u32 value) {
  switch (selector & 7U) {
  case 0: return value ^ 0xa9b7UL;
  case 1: return value ^ 0x9a9bUL;
  case 2: return value ^ 0xc9a9UL;
  case 3: return value ^ 0xec9aUL;
  case 4: return value ^ 0x5ec9UL;
  case 5: return value ^ 0x05ecUL;
  case 6: return value + 0xa9b7UL;
  default: return value - 0x5ec9UL;
  }
}

KEEP u16 generated_type_16_array(u16 seed, u16 selector) {
  u16 values[8];
  u16 i;
  for (i = 0U; i < 8U; ++i)
    values[i] = (u16)(seed + i * 29U);
  values[(selector + 3U) & 7U] ^= (u16)(seed >> (selector & 7U));
  return values[selector & 7U];
}

KEEP u16 generated_type_17_array(u16 seed, u16 selector) {
  u16 values[8];
  u16 i;
  for (i = 0U; i < 8U; ++i)
    values[i] = (u16)(seed + i * 30U);
  values[(selector + 3U) & 7U] ^= (u16)(seed >> (selector & 7U));
  return values[selector & 7U];
}

struct type_18_record { u8 a; u32 b; u16 c; };
KEEP struct type_18_record generated_type_18_struct(
    struct type_18_record value, u16 selector) {
  value.a = (u8)(value.a + selector);
  value.b ^= (u32)selector * 0xd9714cbfUL;
  value.c = (u16)(value.c + (u16)value.b);
  return value;
}

struct type_19_record { u8 a; u32 b; u16 c; };
KEEP struct type_19_record generated_type_19_struct(
    struct type_19_record value, u16 selector) {
  value.a = (u8)(value.a + selector);
  value.b ^= (u32)selector * 0xec386d6dUL;
  value.c = (u16)(value.c + (u16)value.b);
  return value;
}

struct type_20_bits {
  unsigned int a : 3;
  signed int b : 5;
  unsigned int : 0;
  unsigned int c : 9;
};
KEEP u32 generated_type_20_bitfield(struct type_20_bits value, u16 selector) {
  value.a = (unsigned int)(selector & 7U);
  value.c ^= (unsigned int)(selector & 0x1ffU);
  return ((u32)value.a | ((u32)(u16)value.b << 8) |
          ((u32)value.c << 16)) ^ 0xd3220947UL;
}

struct type_21_bits {
  unsigned int a : 3;
  signed int b : 5;
  unsigned int : 0;
  unsigned int c : 9;
};
KEEP u32 generated_type_21_bitfield(struct type_21_bits value, u16 selector) {
  value.a = (unsigned int)(selector & 7U);
  value.c ^= (unsigned int)(selector & 0x1ffU);
  return ((u32)value.a | ((u32)(u16)value.b << 8) |
          ((u32)value.c << 16)) ^ 0xd35ea802UL;
}

struct __attribute__((packed)) type_22_packed {
  u8 a;
  u32 b;
  u16 c;
};
KEEP u32 generated_type_22_packed(struct type_22_packed *value, u16 selector) {
  value->b += (u32)selector + 0x8e8dUL;
  value->c ^= (u16)value->b;
  return value->b + value->a + value->c;
}

struct __attribute__((packed)) type_23_packed {
  u8 a;
  u32 b;
  u16 c;
};
KEEP u32 generated_type_23_packed(struct type_23_packed *value, u16 selector) {
  value->b += (u32)selector + 0x6424UL;
  value->c ^= (u16)value->b;
  return value->b + value->a + value->c;
}

KEEP u32 generated_type_24_pointer(u16 *base, u16 selector) {
  u16 *item = base + (selector & 7U);
  u16 distance = (u16)(item - base);
  *item = (u16)(*item + 0x9468U);
  return (u32)*item | ((u32)distance << 16);
}

KEEP u32 generated_type_25_pointer(u16 *base, u16 selector) {
  u16 *item = base + (selector & 7U);
  u16 distance = (u16)(item - base);
  *item = (u16)(*item + 0xa4c9U);
  return (u32)*item | ((u32)distance << 16);
}

struct type_26_volatile { u16 a; u32 b; u8 c; };
KEEP u32 generated_type_26_volatile(
    volatile struct type_26_volatile *value, u16 selector) {
  u32 prior = value->b;
  value->a = (u16)(value->a ^ selector);
  value->b = prior + 0xb6dcc68dUL;
  return value->b ^ value->a ^ value->c;
}

struct type_27_volatile { u16 a; u32 b; u8 c; };
KEEP u32 generated_type_27_volatile(
    volatile struct type_27_volatile *value, u16 selector) {
  u32 prior = value->b;
  value->a = (u16)(value->a ^ selector);
  value->b = prior + 0xefa340ebUL;
  return value->b ^ value->a ^ value->c;
}

KEEP u32 generated_type_28_goto(u32 value, u16 selector) {
  if (selector & 1U) goto odd;
  value += 0x707205b4UL;
  if (selector & 2U) goto done;
  value ^= value >> 7;
  goto done;
odd:
  value -= 0xd5d7a011UL;
  if (selector & 4U) value ^= value << 9;
done:
  return value;
}

KEEP u32 generated_type_29_goto(u32 value, u16 selector) {
  if (selector & 1U) goto odd;
  value += 0x28572716UL;
  if (selector & 2U) goto done;
  value ^= value >> 7;
  goto done;
odd:
  value -= 0x8df282b3UL;
  if (selector & 4U) value ^= value << 9;
done:
  return value;
}

union type_30_union {
  u32 whole;
  u16 words[2];
  u8 bytes[4];
};
KEEP u32 generated_type_30_union(union type_30_union value, u16 selector) {
  value.words[selector & 1U] ^= (u16)0xa8ccU;
  return value.whole;
}

union type_31_union {
  u32 whole;
  u16 words[2];
  u8 bytes[4];
};
KEEP u32 generated_type_31_union(union type_31_union value, u16 selector) {
  value.words[selector & 1U] ^= (u16)0xb702U;
  return value.whole;
}

typedef u32 (*type_32_callback)(u32, u16);
KEEP u32 type_32_callback_impl(u32 value, u16 selector) {
  return (value + ((u32)selector << 16)) ^
         0x88baf125UL;
}
KEEP u32 generated_type_32_indirect(type_32_callback callback,
                       u32 value, u16 selector) {
  return callback(value ^ 0xb486cd19UL, (u16)(selector + 1U));
}

typedef u32 (*type_33_callback)(u32, u16);
KEEP u32 type_33_callback_impl(u32 value, u16 selector) {
  return (value + ((u32)selector << 16)) ^
         0xf5a296d7UL;
}
KEEP u32 generated_type_33_indirect(type_33_callback callback,
                       u32 value, u16 selector) {
  return callback(value ^ 0xc99eaaebUL, (u16)(selector + 1U));
}

KEEP u32 generated_type_34_recursion(u16 depth, u32 value) {
  value ^= 0x84bb55caUL + depth;
  if ((depth & 7U) == 0U) return value;
  return generated_type_34_recursion((u16)((depth & 7U) - 1U),
                (value << 1) | (value >> 31));
}

KEEP u32 generated_type_35_recursion(u16 depth, u32 value) {
  value ^= 0x2e4e3babUL + depth;
  if ((depth & 7U) == 0U) return value;
  return generated_type_35_recursion((u16)((depth & 7U) - 1U),
                (value << 1) | (value >> 31));
}

__attribute__((noinline, used, section(".llvm_generated_type_entry")))
u32 llvm_generated_type_eval(u16 kernel, u32 a, u32 b, u16 selector) {
  switch (kernel) {
  case 0: return generated_type_00_u8((u8)a, (u8)b);
  case 1: return generated_type_01_u8((u8)a, (u8)b);
  case 2: return (u32)generated_type_02_s8((s8)a, (s8)b);
  case 3: return (u32)generated_type_03_s8((s8)a, (s8)b);
  case 4: return generated_type_04_u16((u16)a, (u16)b);
  case 5: return generated_type_05_u16((u16)a, (u16)b);
  case 6: return (u32)generated_type_06_s16((s16)a, (s16)b);
  case 7: return (u32)generated_type_07_s16((s16)a, (s16)b);
  case 8: return generated_type_08_u32(a, b);
  case 9: return generated_type_09_u32(a, b);
  case 10: return generated_type_10_compare((s32)(s16)a, (s32)(s16)b, selector);
  case 11: return generated_type_11_compare((s32)(s16)a, (s32)(s16)b, selector);
  case 12: return generated_type_12_loop(selector, a);
  case 13: return generated_type_13_loop(selector, a);
  case 14: return generated_type_14_switch(selector, a);
  case 15: return generated_type_15_switch(selector, a);
  case 16: return generated_type_16_array((u16)a, selector);
  case 17: return generated_type_17_array((u16)a, selector);
  case 18: {
    struct type_18_record value;
    value.a = (u8)a; value.b = b; value.c = selector;
    value = generated_type_18_struct(value, selector);
    return value.b ^ ((u32)value.c << 16) ^ value.a;
  }
  case 19: {
    struct type_19_record value;
    value.a = (u8)a; value.b = b; value.c = selector;
    value = generated_type_19_struct(value, selector);
    return value.b ^ ((u32)value.c << 16) ^ value.a;
  }
  case 20: {
    struct type_20_bits value;
    value.a = (unsigned int)(a & 7UL);
    value.b = (signed int)((s16)(b & 31UL) - 16);
    value.c = (unsigned int)((a >> 16) & 0x1ffUL);
    return generated_type_20_bitfield(value, selector);
  }
  case 21: {
    struct type_21_bits value;
    value.a = (unsigned int)(a & 7UL);
    value.b = (signed int)((s16)(b & 31UL) - 16);
    value.c = (unsigned int)((a >> 16) & 0x1ffUL);
    return generated_type_21_bitfield(value, selector);
  }
  case 22: {
    struct type_22_packed value;
    value.a = (u8)a; value.b = b; value.c = (u16)(a >> 8);
    return generated_type_22_packed(&value, selector);
  }
  case 23: {
    struct type_23_packed value;
    value.a = (u8)a; value.b = b; value.c = (u16)(a >> 8);
    return generated_type_23_packed(&value, selector);
  }
  case 24: {
    u16 values[8];
    u16 i;
    for (i = 0U; i < 8U; ++i)
      values[i] = (u16)(a + i * ((u16)b | 1U));
    return generated_type_24_pointer(values, selector);
  }
  case 25: {
    u16 values[8];
    u16 i;
    for (i = 0U; i < 8U; ++i)
      values[i] = (u16)(a + i * ((u16)b | 1U));
    return generated_type_25_pointer(values, selector);
  }
  case 26: {
    volatile struct type_26_volatile value;
    value.a = (u16)a; value.b = b; value.c = (u8)(a >> 24);
    return generated_type_26_volatile(&value, selector);
  }
  case 27: {
    volatile struct type_27_volatile value;
    value.a = (u16)a; value.b = b; value.c = (u8)(a >> 24);
    return generated_type_27_volatile(&value, selector);
  }
  case 28: return generated_type_28_goto(a, selector);
  case 29: return generated_type_29_goto(a, selector);
  case 30: {
    union type_30_union value;
    value.whole = a;
    return generated_type_30_union(value, selector);
  }
  case 31: {
    union type_31_union value;
    value.whole = a;
    return generated_type_31_union(value, selector);
  }
  case 32: return generated_type_32_indirect(type_32_callback_impl, a, selector);
  case 33: return generated_type_33_indirect(type_33_callback_impl, a, selector);
  case 34: return generated_type_34_recursion((u16)(selector & 7U), a);
  case 35: return generated_type_35_recursion((u16)(selector & 7U), a);
  default: return 0xdead7e57UL;
  }
}
