$EXTEND
$NOMOD166
$STDNAMES(reg.def)
$INCLUDE(c166-asm-model.inc)
$CASE
$NOEXPANDREGBANK
; simulator.sh supplies MODEL(...) and TASKING_MODEL_IS_MEDIUM.

        NAME    FLOAT32_CONVERSION_ABI_BOUNDARY

LLVM_PROXY_PR SECTION CODE WORD PUBLIC 'ASMPROG'
        PUBLIC _llvm_f32_to_i32_proxy
        PUBLIC _llvm_f32_to_u32_proxy
        PUBLIC _llvm_f32_to_i16_proxy
        PUBLIC _llvm_f32_to_u16_proxy
        PUBLIC _llvm_i32_to_f32_proxy
        PUBLIC _llvm_u32_to_f32_proxy
        PUBLIC _llvm_i16_to_f32_proxy
        PUBLIC _llvm_u16_to_f32_proxy
        PUBLIC _llvm_f32_compare_proxy

; These typed proxies preserve TASKING's public stack frame while replacing
; only the far call target with the linked LLVM function.
@IF( @TASKING_MODEL_IS_MEDIUM )
_llvm_f32_to_i32_proxy PROC NEAR
        CALLA cc_UC,0C100h
        RET
@ELSE
_llvm_f32_to_i32_proxy PROC FAR
        CALLS 10h,00100h
        RETS
@ENDI
_llvm_f32_to_i32_proxy ENDP

@IF( @TASKING_MODEL_IS_MEDIUM )
_llvm_f32_to_u32_proxy PROC NEAR
        CALLA cc_UC,0C200h
        RET
@ELSE
_llvm_f32_to_u32_proxy PROC FAR
        CALLS 10h,00200h
        RETS
@ENDI
_llvm_f32_to_u32_proxy ENDP

@IF( @TASKING_MODEL_IS_MEDIUM )
_llvm_f32_to_i16_proxy PROC NEAR
        CALLA cc_UC,0C300h
        RET
@ELSE
_llvm_f32_to_i16_proxy PROC FAR
        CALLS 10h,00300h
        RETS
@ENDI
_llvm_f32_to_i16_proxy ENDP

@IF( @TASKING_MODEL_IS_MEDIUM )
_llvm_f32_to_u16_proxy PROC NEAR
        CALLA cc_UC,0C400h
        RET
@ELSE
_llvm_f32_to_u16_proxy PROC FAR
        CALLS 10h,00400h
        RETS
@ENDI
_llvm_f32_to_u16_proxy ENDP

; Integer inputs already occupy their ordinary Classic registers.  Convert
; the public float return R4=MSW,R5=LSW to unsigned-long R4=LSW,R5=MSW.
@IF( @TASKING_MODEL_IS_MEDIUM )
_llvm_i32_to_f32_proxy PROC NEAR
        CALLA cc_UC,0C500h
@ELSE
_llvm_i32_to_f32_proxy PROC FAR
        CALLS 10h,00500h
@ENDI
        MOV R1,R4
        MOV R4,R5
        MOV R5,R1
@IF( @TASKING_MODEL_IS_MEDIUM )
        RET
@ELSE
        RETS
@ENDI
_llvm_i32_to_f32_proxy ENDP

@IF( @TASKING_MODEL_IS_MEDIUM )
_llvm_u32_to_f32_proxy PROC NEAR
        CALLA cc_UC,0C600h
@ELSE
_llvm_u32_to_f32_proxy PROC FAR
        CALLS 10h,00600h
@ENDI
        MOV R1,R4
        MOV R4,R5
        MOV R5,R1
@IF( @TASKING_MODEL_IS_MEDIUM )
        RET
@ELSE
        RETS
@ENDI
_llvm_u32_to_f32_proxy ENDP

@IF( @TASKING_MODEL_IS_MEDIUM )
_llvm_i16_to_f32_proxy PROC NEAR
        CALLA cc_UC,0C700h
@ELSE
_llvm_i16_to_f32_proxy PROC FAR
        CALLS 10h,00700h
@ENDI
        MOV R1,R4
        MOV R4,R5
        MOV R5,R1
@IF( @TASKING_MODEL_IS_MEDIUM )
        RET
@ELSE
        RETS
@ENDI
_llvm_i16_to_f32_proxy ENDP

@IF( @TASKING_MODEL_IS_MEDIUM )
_llvm_u16_to_f32_proxy PROC NEAR
        CALLA cc_UC,0C800h
@ELSE
_llvm_u16_to_f32_proxy PROC FAR
        CALLS 10h,00800h
@ENDI
        MOV R1,R4
        MOV R4,R5
        MOV R5,R1
@IF( @TASKING_MODEL_IS_MEDIUM )
        RET
@ELSE
        RETS
@ENDI
_llvm_u16_to_f32_proxy ENDP

; Signature is exactly (operation, float, float), so R12 and the two
; stack-resident MSW-first operands pass through unchanged.
@IF( @TASKING_MODEL_IS_MEDIUM )
_llvm_f32_compare_proxy PROC NEAR
        CALLA cc_UC,0C900h
        RET
@ELSE
_llvm_f32_compare_proxy PROC FAR
        CALLS 10h,00900h
        RETS
@ENDI
_llvm_f32_compare_proxy ENDP
LLVM_PROXY_PR ENDS

; The LLVM overlay, including compiler-rt, replaces this reserved range.
@IF( @TASKING_MODEL_IS_SMALL )
TASKING_FLOAT_VALUES SECTION LDAT WORD PUBLIC 'FLOATVALUES'
@ELSE
TASKING_FLOAT_VALUES SECTION DATA WORD PUBLIC 'FLOATVALUES'
@ENDI
_tasking_float_values LABEL WORD
; BEGIN GENERATED FLOAT VALUES
; Generated by tools/gen-float32-conversion-vectors.
        DW 00000h,00000h
        DW 08000h,00000h
        DW 00000h,00001h
        DW 03F00h,00000h
        DW 03F80h,00000h
        DW 03FC0h,00000h
        DW 04020h,00000h
        DW 04EFFh,0FFFFh
        DW 0BF00h,00000h
        DW 0BF80h,00000h
        DW 0BFC0h,00000h
        DW 0C020h,00000h
        DW 0CF00h,00000h
        DW 04F00h,00000h
        DW 04F7Fh,0FFFFh
        DW 04640h,0E700h
        DW 046FFh,0FE00h
        DW 0C640h,0E700h
        DW 0C700h,00000h
        DW 0477Fh,0FF00h
        DW 08000h,00001h
        DW 07F7Fh,0FFFFh
        DW 0FF7Fh,0FFFFh
        DW 07F80h,00000h
        DW 0FF80h,00000h
        DW 07FC1h,02345h
        DW 07FA0h,00001h
; END GENERATED FLOAT VALUES
        PUBLIC _tasking_float_values
TASKING_FLOAT_VALUES ENDS

        REGDEF R0-R15
        END
