$EXTEND
$NOMOD166
$STDNAMES(reg.def)
$INCLUDE(c166-asm-model.inc)
$CASE
$NOEXPANDREGBANK
; simulator.sh supplies MODEL(...) directly to a166.
        ASSUME DPP1:C166_XGROUP
        ASSUME DPP2:C166_DGROUP

        NAME    C166_TEST_STARTUP

C166_TEST_STARTUP_PR SECTION CODE WORD PUBLIC 'ASMPROG'
        PUBLIC __CSTART
        ; This is a frame-free tail jump.  The common runner supplies the same
        ; TASKING_MODEL_IS_MEDIUM value to every m166 input; a166 receives the
        ; corresponding MODEL(...) option separately.
@IF( @TASKING_MODEL_IS_MEDIUM )
        EXTERN _main:NEAR
@ELSE
        EXTERN _main:FAR
@ENDI

__CSTART PROC FAR
        MOV STKOV,#?SYSSTACK_BOTTOM + 0Ch
        MOV SP,#?SYSSTACK_TOP
        MOV STKUN,#?SYSSTACK_TOP
        MOV DPP1,#PAG C166_XGROUP
        MOV R0,#POF (?USRSTACK_TOP - 1) + 04001h
        DISWDT
        MOV DPP2,#PAG C166_DGROUP
@IF( @TASKING_MODEL_IS_MEDIUM )
        JMPA    cc_UC,_main
@ELSE
        JMPS    SEG _main,_main
@ENDI
__CSTART ENDP
C166_TEST_STARTUP_PR ENDS

        C166_DGROUP DGROUP __C166_TEST_DUMMY
__C166_TEST_DUMMY SECTION DATA WORD PUBLIC 'CNEAR'
__C166_TEST_DUMMY ENDS

        C166_XGROUP DGROUP __C166_TEST_XDUMMY,C166_US
__C166_TEST_XDUMMY SECTION DATA WORD PUBLIC
__C166_TEST_XDUMMY ENDS
@IF( @TASKING_MODEL_IS_SMALL )
C166_US SECTION LDAT WORD GLBUSRSTACK 'CUSTACK'
@ELSE
C166_US SECTION DATA WORD GLBUSRSTACK 'CUSTACK'
@ENDI
        DS 02h
C166_US ENDS

        REGDEF R0-R15
        END
