if(NOT DEFINED MODEL OR NOT DEFINED INPUT_DIR OR NOT DEFINED LIMITS)
  message(FATAL_ERROR
    "CheckRuntimeClosures.cmake requires MODEL, INPUT_DIR, and LIMITS")
endif()

set(models large medium small tiny huge)
list(FIND models "${MODEL}" model_index)
if(model_index EQUAL -1)
  message(FATAL_ERROR "unsupported memory model: ${MODEL}")
endif()
math(EXPR limit_index "${model_index} + 2")

file(STRINGS "${LIMITS}" rows)
foreach(row IN LISTS rows)
  if(row MATCHES "^helper[	]")
    continue()
  endif()
  string(REPLACE "	" ";" fields "${row}")
  list(GET fields 0 helper)
  list(GET fields ${limit_index} limit)
  set(size_file "${INPUT_DIR}/${helper}.size")
  if(NOT EXISTS "${size_file}")
    message(FATAL_ERROR "missing runtime closure measurement: ${size_file}")
  endif()

  set(actual 0)
  file(STRINGS "${size_file}" sections)
  foreach(section IN LISTS sections)
    if(NOT section MATCHES "^([.][^ 	]+)[ 	]+([0-9]+)[ 	]")
      continue()
    endif()
    set(section_name "${CMAKE_MATCH_1}")
    set(section_size "${CMAKE_MATCH_2}")
    if(section_name MATCHES "^[.](text|rodata|data)([.]|$)" OR
       (section_name MATCHES "^[.]c166[.]" AND
        section_name MATCHES "(^|[.])(text|rodata|data)([.]|$)"))
      math(EXPR actual "${actual} + ${section_size}")
    endif()
  endforeach()
  if(actual EQUAL 0)
    message(SEND_ERROR "${MODEL} ${helper} runtime closure is empty")
  endif()
  message(STATUS "${helper}: ${actual} / ${limit} bytes")
  if(actual GREATER limit)
    message(SEND_ERROR
      "${MODEL} ${helper} runtime closure is ${actual} bytes; limit is ${limit}")
  endif()
endforeach()
