$INCLUDE(c166-asm-architecture.inc)
$INCLUDE(c166-asm-model.inc)
$CASE
        NAME TRAP_VECTORS

; The locator owns vector placement. Each stub is only a flag-neutral jump
; to the LLVM handler; all TRAP instructions under test are in test.S.
TRAP_VECTORS SECTION CODE WORD PUBLIC 'ASMPROG'
VECTOR_1 PROC TASK VECTOR_TASK_1 INTNO VECTOR_INUM_1 = 01H
        JMPS 019H,0000H
VECTOR_1 ENDP
VECTOR_63 PROC TASK VECTOR_TASK_63 INTNO VECTOR_INUM_63 = 03FH
        JMPS 019H,0000H
VECTOR_63 ENDP
VECTOR_127 PROC TASK VECTOR_TASK_127 INTNO VECTOR_INUM_127 = 07FH
        JMPS 019H,0000H
VECTOR_127 ENDP
TRAP_VECTORS ENDS
        END
